apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "vpn1",
          "interface":"net5",
          "cni-args": {
            "interfaceType":"veth",
            "dataplane":"dpdk",
            "mac":"aa:bb:cc:dd:ee:55",
            "ipConfig":{
              "ipv4":{
                "address":"172.31.1.2/24",
                "gateway":"172.31.1.1",
                "routes":[ "172.31.0.0/16","2.2.2.2/32"]
              }
            }
          }
        }
      ]
  labels:
    app: app-odu
  name: app-odu
  namespace: default
spec:
  containers:
    - name: veth-pod
      image: nicolaka/netshoot
      imagePullPolicy: IfNotPresent
      command: ["sleep", "infinity"]
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
        privileged: true
